### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [JakeCrandell/proj7-forms#1]
I broke it. :cry: It looks like when I try to submit a blank form, I get an `Internal Server Error`. I believe [this resource](http://www.w3schools.com/tags/att_input_required.asp) may help you avoid a blank form being submitted.

Let me know when it's updated and I'll take another look.

**Comment by JakeCrandell** [comment]
I put in required attributes for each of the form fields and that should fix the Internal Server Error. Is there anything else I need to update before tomorrow?

**Comment by chrisvfritz** [comment]
Looking better! I also managed to get an `Internal Server Error` when I entered a month larger than 12. I believe [the `min` and `max` attributes](http://www.w3schools.com/tags/att_input_min.asp) for number inputs should help you prevent the user from doing this.

Also, when I submit the form, I expect to see my changes saved in the form, as specified in the project (`every form field should always show the current parameters`). You can do [something like this](https://gist.github.com/chrisvfritz/e36ba5ebf01f86537388) to make sure the current params are reflected in the form.

Let me know when those two are updated and I'll take another look!

**Comment by JakeCrandell** [comment]
Ok, I added the min/max attributes, and I set the values so they save after you submit the form, so those two issues should be all set.  Thanks!

**Comment by chrisvfritz** [comment]
:+1: Looking much better!

**Comment by JakeCrandell** [comment]
Thank you!
